don't include api user and api key as header value to socket.io to resolve cors issues
ftrackhq/ftrack-javascript pull request #109
Opened 2023-05-23 14:25 UTC by jimmycallin

- [ ] I have added automatic tests where applicable
- [ ] The PR title is suitable as a release note
- [ ] The PR contains a description of what has been changed
- [ ] The description contains manual test instructions

## Changes

## Test

2023-05-24 06:35 UTC, gismya approved these changes

2023-05-25 20:43 UTC, ffMathy commented
Is this the final thing needed to get the 1.5 release out of beta? We've been using the package from the server side with a lot of joy and without issues.

2023-05-26 11:18 UTC, lucaas requested changes

2023-05-26 11:18 UTC, lucaas commented on source/simple_socketio.ts
> +      url.searchParams.append("api_key", this.apiKey);
I would like to avoid exposing this as a query param if we can keep it in the header. Does the server not allow them in Access-Control-Allow-Headers?

2023-05-26 11:25 UTC, lucaas commented
> Is this the final thing needed to get the 1.5 release out of beta? We've been using the package from the server side with a lot of joy and without issues.

We're seeing some issues with the new implementation in a browser context (mainly due to differences between XHR/fetch) and will revert to the previous implementation for now. Once those issues have been addressed, we'll get the new implementation merged and released.

2023-05-26 11:26 UTC, jimmycallin commented
Closing this to see if we can resolve the CORS issues server side instead.

2023-05-26 11:26 UTC, closed without merging

2023-05-26 11:28 UTC, ffMathy commented
> > Is this the final thing needed to get the 1.5 release out of beta? We've been using the package from the server side with a lot of joy and without issues.
> 
> We're seeing some issues with the new implementation in a browser context (mainly due to differences between XHR/fetch) and will revert to the previous implementation for now. Once those issues have been addressed, we'll get the new implementation merged and released.

Okay, thanks for the update. Sorry to hear about the issues. Let us know if we can help.

2023-05-26 13:37 UTC, jimmycallin commented
> Oh, and is there an ETA on this? Are we talking years or months or weeks?
> 
> We're converting our codebase from python to typescript, and we're currently using the new typescript client with great success. So we just want to know if we should halt that process for now.

Weeks :) You can still safely use the beta release, for your use case we don't expect to introduce any breaking changes from that. We just want to keep the main channel stable for upcoming patches while we figure out the browser issues with the new socket.io implementation

2023-06-20 10:50 UTC, ffMathy commented
> > Oh, and is there an ETA on this? Are we talking years or months or weeks?
> > 
> > We're converting our codebase from python to typescript, and we're currently using the new typescript client with great success. So we just want to know if we should halt that process for now.
> 
> Weeks :) You can still safely use the beta release, for your use case we don't expect to introduce any breaking changes from that. We just want to keep the main channel stable for upcoming patches while we figure out the browser issues with the new socket.io implementation

Thanks for the update. Looking forward to it! 🙏

2023-07-18 13:59 UTC, ffMathy commented
@jimmycallin how is this going?

2023-07-19 07:29 UTC, gismya commented
Sprint before summer vacations, and then vacations, has put a bit of a wrench in the schedule. I'm hoping we can prioritize this when everyone is back in August.

Until then I can make a pre-release version with the latest version of the client, with the current version of the new socket.io-client if you need it. The issues we've been seeing seem to be contained to browser use of the API, not node use.

2023-07-19 08:31 UTC, ffMathy commented
Oh, didn't see you had just replied here.

Creating a new pre-release version would be awesome!