Add support for async subscriber callbacks while retaining backwards compatibility
ftrackhq/ftrack-javascript pull request #132
Opened 2023-07-21 07:31 UTC by ffMathy

Add support for async subscriber callbacks while retaining backwards compatibility.

- [ ] I have added automatic tests where applicable
- [X] The PR title is suitable as a release note
- [X] The PR contains a description of what has been changed
- [X] The description contains manual test instructions

## Changes
Made it possible to have an async subscriber callback.

## Test
Check if subscribers are still called.

2023-07-21 07:58 UTC, gismya commented
Looks great!

Will probably be a few weeks before this can be reviewed and merged. I won't have time to do it before going on summer vacations and the other maintainers are already on vacations.

2023-08-28 12:35 UTC, gismya requested changes
Looking good. Please add tests for handling both async and non async callbacks.

2023-08-28 13:49 UTC, ffMathy commented
Okay. I looked at the existing tests, and I couldn't find enough inspiration to get started with this easily.

Do you have an idea of where I can start? The existing tests don't seem to have an example that tests the return value of the callback itself, and if that is being replied.

2023-08-28 17:08 UTC, gismya commented
Something like this should work

```
  test("should handle async callback and return correct data", () => {
    const callback = vi.fn(async () => {
      return new Promise((resolve) => setTimeout(() => resolve("someData"), 1));
    });
    const testEvent = {
      topic: "ftrack.test",
      data: {},
      id: "eventId",
      source: { id: "sourceId" },
    };

    const publishReplySpy = vi
      .spyOn(eventHub, "publishReply")
      .mockImplementation((_, data) => data);

    eventHub.subscribe("topic=ftrack.test", callback);
    eventHub._handle(testEvent);

    setTimeout(() => {
      expect(callback).toHaveBeenCalledWith(testEvent);
      expect(publishReplySpy).toHaveBeenCalledWith(
        expect.anything(),
        "someData",
        expect.anything()
      );
    }, 10);
    publishReplySpy.mockRestore();
  });

  test("should handle sync callback and return correct data", () => {
    const callback = vi.fn(() => "someData");
    const testEvent = {
      topic: "ftrack.test",
      data: {},
      id: "eventId",
      source: { id: "sourceId" },
    };

    const publishReplySpy = vi
      .spyOn(eventHub, "publishReply")
      .mockImplementation((_, data) => data);

    eventHub.subscribe("topic=ftrack.test", callback);
    eventHub._handle(testEvent);

    setTimeout(() => {
      expect(callback).toHaveBeenCalledWith(testEvent);
      expect(publishReplySpy).toHaveBeenCalledWith(
        expect.anything(),
        "someData",
        expect.anything()
      );
    }, 10);
    publishReplySpy.mockRestore();
  });
});
```

Not the prettiest tests, but without changing the return values we have no way of awaiting everything, so there's a magic 10 ms timeout.

2023-08-29 06:54 UTC, gismya requested changes
Didn't actually test the test properly yesterday. It incorrectly passed even when a promise was sent as a response to publishReply, and didn't correctly check the value either. Adding the promises as return value for the function and awaiting (With some other changes) made the tests work as intended.

Good catch with .ts missing from lint-staged. I wonder why you need `npx` in the command though - could you check that you've done `npm install` (Or 'yarn' if that's what you're using) and that it's simply not missing the needed node modules? Otherwise I'll investigate if there might be any issues with using `npx` together with Yarn.

2023-08-29 06:54 UTC, gismya commented on test/event_hub.test.js
> +  });
```suggestion
  test("should handle sync callback and return correct data", async () => {
    const callback = vi.fn(() => "someData");
    const testEvent = {
      topic: "ftrack.test",
      data: {},
      id: "eventId",
      source: { id: "sourceId" },
    };

    const publishReplySpy = vi
      .spyOn(eventHub, "publishReply")
      .mockImplementation((_, data) => data);

    eventHub.subscribe("topic=ftrack.test", callback);
    const promises = eventHub._handle(testEvent);
    await Promise.all(promises);
    expect(callback).toHaveBeenCalledWith(testEvent);
    expect(publishReplySpy).toHaveBeenCalledWith(
      expect.anything(),
      "someData",
      expect.anything()
    );
    publishReplySpy.mockRestore();
  });

  test("should not handle async callback with a promise", async () => {
    const asyncCallback = vi.fn(async () => "someData");
    const testEvent = {
      topic: "ftrack.test",
      data: {},
      id: "eventId",
      source: { id: "sourceId" },
    };

    const publishReplySpy = vi
      .spyOn(eventHub, "publishReply")
      .mockImplementation((_, data) => data);

    eventHub.subscribe("topic=ftrack.test", asyncCallback);
    const promises = eventHub._handle(testEvent);
    await Promise.all(promises ?? []);
    expect(asyncCallback).toHaveBeenCalledWith(testEvent);
    expect(publishReplySpy).toHaveBeenCalled();
    expect(publishReplySpy).not.toHaveBeenCalledWith(
      expect.anything(),
      expect.any(Promise),
      expect.anything()
    );
    expect(publishReplySpy).toHaveBeenCalledWith(
      expect.anything(),
      "someData",
      expect.anything()
    );
    publishReplySpy.mockRestore();
  });
```

2023-08-29 06:54 UTC, gismya commented on source/event_hub.ts
```suggestion
    const promises: Promise<any>[] = [];
```

2023-08-29 06:54 UTC, gismya commented on source/event_hub.ts
> +
```suggestion
                promises.push(responsePromise);
```

2023-08-29 06:54 UTC, gismya commented on source/event_hub.ts
>      }
```suggestion
         return promises; 
    }
```

2023-08-29 08:14 UTC, gismya approved these changes
I did some mistakes when line by line suggesting the promise returns. I've commited the correct implementation.

You can remove the changes to package.json - we identified that the commit hooks have more issues and I'm posting a separate PR for that shortly. Thank you for pointing that out! Our IDE setups made us miss that it didn't run correctly.

2023-08-29 08:43 UTC, merged

2023-08-29 09:02 UTC, ffMathy commented
Thanks for this!