Support use blob to createComponent
ftrackhq/ftrack-javascript pull request #20
Opened 2022-09-04 10:08 UTC by WaylonFtrack

2022-09-22 15:02 UTC, jimmycallin commented
Hi @WaylonFtrack! Would you mind looking into getting the tests for file uploading to work (they are currently skipped), and add an additional test for blobs? Thanks!

2022-09-22 15:02 UTC, jimmycallin requested changes
Hi @WaylonFtrack! Would you mind looking into getting the tests for file uploading to work (they are currently skipped), and add an additional test for blobs? Thanks!

2022-09-23 08:38 UTC, lucaas commented
Is the goal to add support for browsers not supporting the [File constructor](https://developer.mozilla.org/en-US/docs/Web/API/File), or what is the motivation for the change?

2022-09-23 10:47 UTC, WaylonFtrack commented
I was trying to upload canvas image from [HTMLCanvasElement.toBlob](https://devdocs.io/dom/htmlcanvaselement/toblob). Since file constructor is additional wrapper, and the changes to directly support `Blob` are minimal and compatible with `File`, I submitted this PR.

2022-09-23 10:50 UTC, WaylonFtrack commented on source/session.js
> +      let progress = 0;
jsdom won't set request headers before `request`, cause `onProgress` never be called in test enviroment.

2022-09-26 10:51 UTC, jimmycallin approved these changes
I'm happy with this, but would like @lucaas to approve as well! Good job with the tests as well!

2022-09-26 13:59 UTC, lucaas commented
> I was trying to upload canvas image from [HTMLCanvasElement.toBlob](https://devdocs.io/dom/htmlcanvaselement/toblob). Since file constructor is additional wrapper, and the changes to directly support `Blob` are minimal and compatible with `File`, I submitted this PR.

I see. In the review player, we also use `canvas.toBlob`, but duck-type it as a File by [just setting blob.name](https://github.com/ftrackhq/frontend/blob/35ff23182d510cbb16329540415152036b9fa7b7/packages/overview/source/lib/cso/export_annotation.js#L24-L29). This is a cleaner solution, so happy to accept it.

2022-09-26 14:03 UTC, lucaas approved these changes

2022-09-26 15:11 UTC, merged